version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  php-cli:
    image: php:8.2-cli
    container_name: php-cli
    volumes:
      - ./shared:/var/www/shared
    working_dir: /var/www/shared
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./website1:/var/www/html
    depends_on:
      - website1
    ports:
      - "8080:80"

  website1:
    image: php:8.2-fpm
    container_name: website1
    restart: always
    volumes:
      - ./website1:/var/www/html
    environment:
      DB_HOST: mariadb
      DB_DATABASE: website1_db
      DB_USER: website1_user
      DB_PASSWORD: password1
    depends_on:
      - mariadb

  website2:
    image: dunglas/frankenphp:latest
    container_name: website2
    restart: always
    volumes:
      - ./website2:/var/www/html
    environment:
      DB_HOST: mariadb
      DB_DATABASE: website2_db
      DB_USER: website2_user
      DB_PASSWORD: password2
    depends_on:
      - mariadb
    ports:
      - "8090:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
