version: '3.7'
services:
  php_docker:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_docker
    hostname: "php"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    environment:
      DB_HOST: mysql_docker
      DB_DATABASE: clover
      DB_USER: root
      DB_PASSWORD: 123456
    networks:
      - app-network

  nginx_docker:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_docker
    hostname: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
