version: '3.9'

services:
  php_laravel:
    build:
      context: ./php
      dockerfile: Dockerfile  # Perbaiki nama file, gunakan huruf besar "D"
    container_name: php_laravel
    hostname: "php"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    networks:
      - app-network

  nginx_laravel:
    build:
      context: ./nginx
      dockerfile: Dockerfile  # Sama, pastikan huruf besar "D"
    container_name: nginx_laravel
    hostname: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_laravel  # Pastikan PHP berjalan sebelum Nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
